name: CI

on:
  push:
    branches:
      - main
      - 'v*'
  pull_request: {}

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    env:
      ENV: test

    steps:
      - uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.x

      - name: Tests
        run: go test -v ./...
