name: CI

on:
  push:
    branches:
      - main
      - 'v*'
  pull_request: {}

jobs:
  test:
    name: Tests in Go ${{ matrix.go }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        go: [ '1.13', '1.12' ]
        os: [ubuntu-latest, macos-latest, windows-latest]

    env:
      ENV: test

    steps:
      - uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go}}

      - name: Tests
        run: go test -v ./...
